install:
  - ps: Start-FileDownload 'http://neo4j.com/artifact.php?name=neo4j-community-2.1.5-windows.zip' -FileName 'neo4j.zip'
  - cmd: 7z x c:\projects\CypherNet\neo4j.zip
  - cmd: c:\projects\CypherNet\neo4j-community-2.1.5\bin\Neo4jInstaller.bat install