install:
  - ps: Start-FileDownload 'http://neo4j.com/artifact.php?name=neo4j-community-2.3.2-windows.zip' -FileName 'c:\projects\CypherNet\neo4j-community-2.3.2-windows.zip'
  - cmd: 7z x c:\projects\CypherNet\neo4j-community-2.3.2-windows.zip
  - cmd: c:\projects\CypherNet\neo4j-community-2.3.2\bin\Neo4jInstaller.bat install
  - ps: .\update-pwd.ps1
  
build:
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
